#############################################################################
# Makefile for building: u59
# Generated by qmake (2.01a) (Qt 4.8.7) on: Sun Jan 22 13:30:07 2017
# Project:  u59.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile u59.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe `llvm-config --cxxflags` -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Iinclude -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu `llvm-config --ldflags --libs core` -ldl -lncurses -std=c++11 -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/ar.cpp \
		src/arproto.cpp \
		src/block.cpp \
		src/blockbody.cpp \
		src/ciproto.cpp \
		src/constint.cpp \
		src/expr.cpp \
		src/guimanager.cpp \
		src/guiobj.cpp \
		src/llvmunit.cpp \
		src/main.cpp \
		src/proto.cpp \
		src/protomanager.cpp \
		src/type.cpp \
		src/varint.cpp \
		src/viproto.cpp \
		src/window.cpp 
OBJECTS       = ar.o \
		arproto.o \
		block.o \
		blockbody.o \
		ciproto.o \
		constint.o \
		expr.o \
		guimanager.o \
		guiobj.o \
		llvmunit.o \
		main.o \
		proto.o \
		protomanager.o \
		type.o \
		varint.o \
		viproto.o \
		window.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		u59.pro
QMAKE_TARGET  = u59
DESTDIR       = 
TARGET        = u59

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: u59.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile u59.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile u59.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/u591.0.0 || $(MKDIR) .tmp/u591.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/u591.0.0/ && $(COPY_FILE) --parents include/ar.h include/arproto.h include/block.h include/blockbody.h include/ciproto.h include/constint.h include/expr.h include/guimanager.h include/guiobj.h include/llvm.h include/llvmunit.h include/proto.h include/protomanager.h include/type.h include/varint.h include/viproto.h include/window.h .tmp/u591.0.0/ && $(COPY_FILE) --parents src/ar.cpp src/arproto.cpp src/block.cpp src/blockbody.cpp src/ciproto.cpp src/constint.cpp src/expr.cpp src/guimanager.cpp src/guiobj.cpp src/llvmunit.cpp src/main.cpp src/proto.cpp src/protomanager.cpp src/type.cpp src/varint.cpp src/viproto.cpp src/window.cpp .tmp/u591.0.0/ && (cd `dirname .tmp/u591.0.0` && $(TAR) u591.0.0.tar u591.0.0 && $(COMPRESS) u591.0.0.tar) && $(MOVE) `dirname .tmp/u591.0.0`/u591.0.0.tar.gz . && $(DEL_FILE) -r .tmp/u591.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

ar.o: src/ar.cpp include/ar.h \
		include/block.h \
		include/guiobj.h \
		include/proto.h \
		include/expr.h \
		include/llvm.h \
		include/blockbody.h \
		include/llvmunit.h \
		include/type.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ar.o src/ar.cpp

arproto.o: src/arproto.cpp include/arproto.h \
		include/proto.h \
		include/guiobj.h \
		include/type.h \
		include/blockbody.h \
		include/guimanager.h \
		include/llvm.h \
		include/ar.h \
		include/block.h \
		include/expr.h \
		include/protomanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o arproto.o src/arproto.cpp

block.o: src/block.cpp include/block.h \
		include/guiobj.h \
		include/blockbody.h \
		include/guimanager.h \
		include/llvm.h \
		include/type.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o block.o src/block.cpp

blockbody.o: src/blockbody.cpp include/blockbody.h \
		include/expr.h \
		include/llvm.h \
		include/llvmunit.h \
		include/type.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o blockbody.o src/blockbody.cpp

ciproto.o: src/ciproto.cpp include/ciproto.h \
		include/proto.h \
		include/guiobj.h \
		include/type.h \
		include/blockbody.h \
		include/constint.h \
		include/block.h \
		include/expr.h \
		include/llvm.h \
		include/guimanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ciproto.o src/ciproto.cpp

constint.o: src/constint.cpp include/constint.h \
		include/block.h \
		include/guiobj.h \
		include/blockbody.h \
		include/expr.h \
		include/llvm.h \
		include/guimanager.h \
		include/type.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o constint.o src/constint.cpp

expr.o: src/expr.cpp include/expr.h \
		include/llvm.h \
		include/block.h \
		include/guiobj.h \
		include/blockbody.h \
		include/llvmunit.h \
		include/type.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o expr.o src/expr.cpp

guimanager.o: src/guimanager.cpp include/guimanager.h \
		include/llvm.h \
		include/guiobj.h \
		include/protomanager.h \
		include/block.h \
		include/blockbody.h \
		include/expr.h \
		include/llvmunit.h \
		include/proto.h \
		include/type.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o guimanager.o src/guimanager.cpp

guiobj.o: src/guiobj.cpp include/guiobj.h \
		include/guimanager.h \
		include/llvm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o guiobj.o src/guiobj.cpp

llvmunit.o: src/llvmunit.cpp include/llvmunit.h \
		include/llvm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o llvmunit.o src/llvmunit.cpp

main.o: src/main.cpp include/window.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

proto.o: src/proto.cpp include/proto.h \
		include/guiobj.h \
		include/block.h \
		include/blockbody.h \
		include/guimanager.h \
		include/llvm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o proto.o src/proto.cpp

protomanager.o: src/protomanager.cpp include/protomanager.h \
		include/blockbody.h \
		include/ciproto.h \
		include/proto.h \
		include/guiobj.h \
		include/type.h \
		include/expr.h \
		include/llvm.h \
		include/viproto.h \
		include/arproto.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o protomanager.o src/protomanager.cpp

type.o: src/type.cpp include/type.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o type.o src/type.cpp

varint.o: src/varint.cpp include/varint.h \
		include/block.h \
		include/guiobj.h \
		include/proto.h \
		include/expr.h \
		include/llvm.h \
		include/blockbody.h \
		include/llvmunit.h \
		include/type.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o varint.o src/varint.cpp

viproto.o: src/viproto.cpp include/viproto.h \
		include/proto.h \
		include/guiobj.h \
		include/type.h \
		include/blockbody.h \
		include/guimanager.h \
		include/llvm.h \
		include/varint.h \
		include/block.h \
		include/expr.h \
		include/protomanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o viproto.o src/viproto.cpp

window.o: src/window.cpp include/window.h \
		include/guimanager.h \
		include/llvm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o window.o src/window.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

